version: "3"
services:
  app:
    image: node:12
    user: node
    #env_file: ./app.env
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    tty: true
    #expose:
    #  - '8080'
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "npm start"
